# Generated by Django 6.1 on 2026-09-08 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('goal', 'position')},
        ),
    ]
